In [1]:
import pandas as pd
import numpy as np

In [2]:
d=pd.read_csv("titanic.csv")

In [3]:
d.head()

Survived                                               Name     Sex  \
0         0                             Mr. Owen Harris Braund    male   
1         1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female   
2         1                              Miss. Laina Heikkinen  female   
3         1        Mrs. Jacques Heath (Lily May Peel) Futrelle  female   
4         0                            Mr. William Henry Allen    male   

   Siblings/Spouses Aboard  Parents/Children Aboard     Fare  Pclass   Age  
0                        1                        0   7.2500       3  22.0  
1                        1                        0  71.2833       1  38.0  
2                        0                        0   7.9250       3  26.0  
3                        1                        0  53.1000       1  35.0  
4                        0                        0   8.0500       3  35.0

In [6]:
d.isnull().any()

Survived                   False
Name                       False
Sex                        False
Siblings/Spouses Aboard    False
Parents/Children Aboard    False
Fare                       False
Pclass                     False
Age                        False
dtype: bool

In [7]:
x=d.iloc[:,2:8].values
y=d.iloc[:,0:1].values

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[0])],remainder = "passthrough") # conerts data to binary format
x = ct.fit_transform(x)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [20]:
ann=Sequential()

In [21]:
ann.add(Dense(7,kernel_initializer = "random_uniform", activation ="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [22]:
ann.add(Dense(14,kernel_initializer = "random_uniform", activation ="relu"))

In [23]:
ann.add(Dense(1,kernel_initializer = "random_uniform", activation ="sigmoid"))

In [24]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [25]:
ann.fit(x_train,y_train,batch_size=32,epochs=40)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/40
709/709 [==============================] - 0s 299us/sample - loss: 0.6916 - acc: 0.6037
Epoch 2/40
709/709 [==============================] - 0s 32us/sample - loss: 0.6860 - acc: 0.6037
Epoch 3/40
709/709 [==============================] - 0s 36us/sample - loss: 0.6697 - acc: 0.6037
Epoch 4/40
709/709 [==============================] - 0s 41us/sample - loss: 0.6342 - acc: 0.6037
Epoch 5/40
709/709 [==============================] - 0s 38us/sample - loss: 0.5852 - acc: 0.6671
Epoch 6/40
709/709 [==============================] - 0s 41us/sample - loss: 0.5471 - acc: 0.7814
Epoch 7/40
709/709 [==============================] - 0s 35us/sample - loss: 0.5280 - acc: 0.8082
Epoch 8/40
709/709 [==============================] - 0s 39us/sample - loss: 0.5181 - acc: 0.8039
Epoch 9/40
709/709 [==============================] - 0s 37us/sample - loss: 0.5087 - acc: 0.8011
Epoch 10/40
709/709 [==

In [26]:
ypred=ann.predict(x_test)

In [30]:
d.head(1)

Survived                    Name   Sex  Siblings/Spouses Aboard  \
0         0  Mr. Owen Harris Braund  male                        1   

   Parents/Children Aboard  Fare  Pclass   Age  
0                        0  7.25       3  22.0

In [31]:
yp=ann.predict(sc.transform(ct.transform([["male",1,0,7.25,3,22]])))

In [32]:
yp

array([[0.11278737]], dtype=float32)

In [33]:
yp>0.5

array([[False]])

In [34]:
d.head()

Survived                                               Name     Sex  \
0         0                             Mr. Owen Harris Braund    male   
1         1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female   
2         1                              Miss. Laina Heikkinen  female   
3         1        Mrs. Jacques Heath (Lily May Peel) Futrelle  female   
4         0                            Mr. William Henry Allen    male   

   Siblings/Spouses Aboard  Parents/Children Aboard     Fare  Pclass   Age  
0                        1                        0   7.2500       3  22.0  
1                        1                        0  71.2833       1  38.0  
2                        0                        0   7.9250       3  26.0  
3                        1                        0  53.1000       1  35.0  
4                        0                        0   8.0500       3  35.0

In [35]:
yp=ann.predict(sc.transform(ct.transform([["female",1,0,71.2833,1,38]])))

In [36]:
yp

array([[0.96325874]], dtype=float32)

In [37]:
yp>0.5

array([[ True]])