In [1]:
import pandas as pd
import numpy as np

In [2]:
d=pd.read_csv(r"nba_logreg.csv")

In [3]:
d.head()

name  gp   min  pts  fgm  fga    fg  3p_made  3pa    3p  ...  \
0   Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   
1  Andrew Harrison  35  26.9  7.2  2.0  6.7  29.6      0.7  2.8  23.5  ...   
2   JaKarr Sampson  74  15.3  5.2  2.0  4.7  42.2      0.4  1.7  24.4  ...   
3      Malik Sealy  58  11.6  5.7  2.3  5.5  42.6      0.1  0.5  22.6  ...   
4      Matt Geiger  48  11.5  4.5  1.6  3.0  52.4      0.0  0.1   0.0  ...   

   fta    ft  oreb  dreb  reb  ast  stl  blk  tov  target_5yrs  
0  2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3          0.0  
1  3.4  76.5   0.5   2.0  2.4  3.7  1.1  0.5  1.6          0.0  
2  1.3  67.0   0.5   1.7  2.2  1.0  0.5  0.3  1.0          0.0  
3  1.3  68.9   1.0   0.9  1.9  0.8  0.6  0.1  1.0          1.0  
4  1.9  67.4   1.0   1.5  2.5  0.3  0.3  0.4  0.8          1.0  

[5 rows x 21 columns]

In [4]:
d.isnull().sum()

name            0
gp              0
min             0
pts             0
fgm             0
fga             0
fg              0
3p_made         0
3pa             0
3p             11
ftm             0
fta             0
ft              0
oreb            0
dreb            0
reb             0
ast             0
stl             0
blk             0
tov             0
target_5yrs     0
dtype: int64

In [6]:
d["3p"].fillna(d["3p"].mean(),inplace = True)

In [13]:
x=d.iloc[:,1:20].values
y=d.iloc[:,20].values

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [20]:
ann=Sequential()

In [21]:
ann.add(Dense(19,kernel_initializer = "random_uniform", activation ="relu"))

In [24]:
ann.add(Dense(38,kernel_initializer = "random_uniform", activation ="relu"))

In [25]:
ann.add(Dense(1,kernel_initializer = "random_uniform", activation ="sigmoid"))

In [26]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [29]:
ann.fit(x_train,y_train,batch_size=32,epochs=500)

Epoch 1/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5112 - accuracy: 0.7519
Epoch 2/500
34/34 [==============================] - 0s 855us/step - loss: 0.5115 - accuracy: 0.7453
Epoch 3/500
34/34 [==============================] - 0s 912us/step - loss: 0.5111 - accuracy: 0.7472
Epoch 4/500
34/34 [==============================] - 0s 844us/step - loss: 0.5114 - accuracy: 0.7463
Epoch 5/500
34/34 [==============================] - 0s 872us/step - loss: 0.5098 - accuracy: 0.7519
Epoch 6/500
34/34 [==============================] - 0s 786us/step - loss: 0.5092 - accuracy: 0.7509
Epoch 7/500
34/34 [==============================] - 0s 858us/step - loss: 0.5088 - accuracy: 0.7425
Epoch 8/500
34/34 [==============================] - 0s 812us/step - loss: 0.5082 - accuracy: 0.7547
Epoch 9/500
34/34 [==============================] - 0s 869us/step - loss: 0.5089 - accuracy: 0.7509
Epoch 10/500
34/34 [==============================] - 0s 867us/step - loss: 0.5084 - accuracy

34/34 [==============================] - 0s 979us/step - loss: 0.4900 - accuracy: 0.7612
Epoch 82/500
34/34 [==============================] - 0s 965us/step - loss: 0.4890 - accuracy: 0.7640
Epoch 83/500
34/34 [==============================] - 0s 833us/step - loss: 0.4897 - accuracy: 0.7631
Epoch 84/500
34/34 [==============================] - 0s 870us/step - loss: 0.4892 - accuracy: 0.7584
Epoch 85/500
34/34 [==============================] - 0s 824us/step - loss: 0.4898 - accuracy: 0.7649
Epoch 86/500
34/34 [==============================] - 0s 862us/step - loss: 0.4873 - accuracy: 0.7640
Epoch 87/500
34/34 [==============================] - 0s 742us/step - loss: 0.4891 - accuracy: 0.7659
Epoch 88/500
34/34 [==============================] - 0s 781us/step - loss: 0.4887 - accuracy: 0.7659
Epoch 89/500
34/34 [==============================] - 0s 791us/step - loss: 0.4879 - accuracy: 0.7640
Epoch 90/500
34/34 [==============================] - 0s 772us/step - loss: 0.4895 - accuracy: 

34/34 [==============================] - 0s 766us/step - loss: 0.4761 - accuracy: 0.7743
Epoch 161/500
34/34 [==============================] - 0s 773us/step - loss: 0.4768 - accuracy: 0.7715
Epoch 162/500
34/34 [==============================] - 0s 751us/step - loss: 0.4757 - accuracy: 0.7733
Epoch 163/500
34/34 [==============================] - 0s 716us/step - loss: 0.4753 - accuracy: 0.7733
Epoch 164/500
34/34 [==============================] - 0s 793us/step - loss: 0.4766 - accuracy: 0.7668
Epoch 165/500
34/34 [==============================] - 0s 765us/step - loss: 0.4749 - accuracy: 0.7705
Epoch 166/500
34/34 [==============================] - 0s 699us/step - loss: 0.4747 - accuracy: 0.7640
Epoch 167/500
34/34 [==============================] - 0s 722us/step - loss: 0.4743 - accuracy: 0.7696
Epoch 168/500
34/34 [==============================] - 0s 720us/step - loss: 0.4736 - accuracy: 0.7677
Epoch 169/500
34/34 [==============================] - 0s 722us/step - loss: 0.4756 - a

34/34 [==============================] - 0s 669us/step - loss: 0.4668 - accuracy: 0.7687
Epoch 240/500
34/34 [==============================] - 0s 706us/step - loss: 0.4647 - accuracy: 0.7677
Epoch 241/500
34/34 [==============================] - 0s 737us/step - loss: 0.4660 - accuracy: 0.7696
Epoch 242/500
34/34 [==============================] - 0s 728us/step - loss: 0.4675 - accuracy: 0.7612
Epoch 243/500
34/34 [==============================] - 0s 738us/step - loss: 0.4657 - accuracy: 0.7668
Epoch 244/500
34/34 [==============================] - 0s 738us/step - loss: 0.4661 - accuracy: 0.7677
Epoch 245/500
34/34 [==============================] - 0s 734us/step - loss: 0.4651 - accuracy: 0.7621
Epoch 246/500
34/34 [==============================] - 0s 743us/step - loss: 0.4686 - accuracy: 0.7640
Epoch 247/500
34/34 [==============================] - 0s 759us/step - loss: 0.4664 - accuracy: 0.7649
Epoch 248/500
34/34 [==============================] - 0s 736us/step - loss: 0.4648 - a

34/34 [==============================] - 0s 706us/step - loss: 0.4579 - accuracy: 0.7724
Epoch 319/500
34/34 [==============================] - 0s 774us/step - loss: 0.4607 - accuracy: 0.7668
Epoch 320/500
34/34 [==============================] - 0s 720us/step - loss: 0.4595 - accuracy: 0.7705
Epoch 321/500
34/34 [==============================] - 0s 709us/step - loss: 0.4576 - accuracy: 0.7743
Epoch 322/500
34/34 [==============================] - 0s 738us/step - loss: 0.4568 - accuracy: 0.7761
Epoch 323/500
34/34 [==============================] - 0s 745us/step - loss: 0.4600 - accuracy: 0.7696
Epoch 324/500
34/34 [==============================] - 0s 664us/step - loss: 0.4591 - accuracy: 0.7771
Epoch 325/500
34/34 [==============================] - 0s 765us/step - loss: 0.4605 - accuracy: 0.7789
Epoch 326/500
34/34 [==============================] - 0s 718us/step - loss: 0.4575 - accuracy: 0.7705
Epoch 327/500
34/34 [==============================] - 0s 724us/step - loss: 0.4592 - a

34/34 [==============================] - 0s 744us/step - loss: 0.4555 - accuracy: 0.7733
Epoch 398/500
34/34 [==============================] - 0s 716us/step - loss: 0.4555 - accuracy: 0.7771
Epoch 399/500
34/34 [==============================] - 0s 691us/step - loss: 0.4548 - accuracy: 0.7761
Epoch 400/500
34/34 [==============================] - 0s 768us/step - loss: 0.4535 - accuracy: 0.7733
Epoch 401/500
34/34 [==============================] - 0s 727us/step - loss: 0.4514 - accuracy: 0.7808
Epoch 402/500
34/34 [==============================] - 0s 741us/step - loss: 0.4519 - accuracy: 0.7799
Epoch 403/500
34/34 [==============================] - 0s 781us/step - loss: 0.4516 - accuracy: 0.7752
Epoch 404/500
34/34 [==============================] - 0s 707us/step - loss: 0.4514 - accuracy: 0.7761
Epoch 405/500
34/34 [==============================] - 0s 706us/step - loss: 0.4518 - accuracy: 0.7752
Epoch 406/500
34/34 [==============================] - 0s 730us/step - loss: 0.4511 - a

34/34 [==============================] - 0s 761us/step - loss: 0.4472 - accuracy: 0.7799
Epoch 477/500
34/34 [==============================] - 0s 790us/step - loss: 0.4464 - accuracy: 0.7826
Epoch 478/500
34/34 [==============================] - 0s 723us/step - loss: 0.4511 - accuracy: 0.7845
Epoch 479/500
34/34 [==============================] - 0s 795us/step - loss: 0.4523 - accuracy: 0.7705
Epoch 480/500
34/34 [==============================] - 0s 721us/step - loss: 0.4483 - accuracy: 0.7724
Epoch 481/500
34/34 [==============================] - 0s 706us/step - loss: 0.4464 - accuracy: 0.7836
Epoch 482/500
34/34 [==============================] - 0s 695us/step - loss: 0.4466 - accuracy: 0.7789
Epoch 483/500
34/34 [==============================] - 0s 755us/step - loss: 0.4480 - accuracy: 0.7836
Epoch 484/500
34/34 [==============================] - 0s 773us/step - loss: 0.4472 - accuracy: 0.7808
Epoch 485/500
34/34 [==============================] - 0s 705us/step - loss: 0.4475 - a

In [30]:
ypred=ann.predict(x_test)

In [31]:
d.head(1)

name  gp   min  pts  fgm  fga    fg  3p_made  3pa    3p  ...  \
0  Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   

   fta    ft  oreb  dreb  reb  ast  stl  blk  tov  target_5yrs  
0  2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3          0.0  

[1 rows x 21 columns]

In [33]:
yp=ann.predict(sc.transform([[36,274,7.4,2.6,7.6,34.7,0.5,2.1,25.0,1.6,2.3,69.9,0.7,3.4,4.1,1.9,0.1,0.4,1.3]]))

In [34]:
yp

array([[1.7940434e-07]], dtype=float32)

In [35]:
yp>0.5

array([[False]])

In [38]:
yp=ann.predict(sc.transform([[40,280,7.9,3.6,44.7,8.5,5.1,55.0,5.6,2.8,69.7,2.7,5.4,2.1,8.9,0.3,0.2,1.5,5.2]]))

In [39]:
yp>0.5

array([[ True]])